-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 19:05:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema registrationdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registrationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registrationdb` DEFAULT CHARACTER SET utf8mb3 ;
USE `registrationdb` ;

-- -----------------------------------------------------
-- Table `registrationdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`users` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `first_login` TINYINT NOT NULL DEFAULT '1',
  `sess_ver` INT NOT NULL DEFAULT '0',
  `last_login_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 151
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`admins` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`admins` (
  `user_id` INT NOT NULL,
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `access_level` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`employee_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1007
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`courses` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`courses` (
  `course_id` INT NOT NULL AUTO_INCREMENT,
  `course_code` VARCHAR(10) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `credits` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_code_UNIQUE` (`course_code` ASC) VISIBLE,
  UNIQUE INDEX `course_code` (`course_code` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 125
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`professors` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`professors` (
  `user_id` INT NOT NULL,
  `professor_id` INT NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`professor_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_professors_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1024
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`semesters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`semesters` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`semesters` (
  `semester_id` INT NOT NULL AUTO_INCREMENT,
  `term` VARCHAR(8) NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`semester_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`sections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`sections` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`sections` (
  `section_id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `semester_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  `capacity` INT NULL DEFAULT NULL,
  `days` VARCHAR(10) NOT NULL,
  `start_time` TIME NULL DEFAULT NULL,
  `end_time` TIME NULL DEFAULT NULL,
  `access_codes` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`section_id`),
  INDEX `professor_id_idx` (`professor_id` ASC) VISIBLE,
  INDEX `semester_id_idx` (`semester_id` ASC) VISIBLE,
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_sections_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_sections_professor`
    FOREIGN KEY (`professor_id`)
    REFERENCES `registrationdb`.`professors` (`professor_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_sections_semester`
    FOREIGN KEY (`semester_id`)
    REFERENCES `registrationdb`.`semesters` (`semester_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5627
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`students` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`students` (
  `user_id` INT NOT NULL,
  `student_id` INT NOT NULL AUTO_INCREMENT,
  `major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`student_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 10000248
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`enrollments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`enrollments` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`enrollments` (
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `section_id` INT NOT NULL,
  `status` ENUM('enrolled', 'dropped', 'completed', 'waitlisted') NOT NULL,
  PRIMARY KEY (`enrollment_id`),
  UNIQUE INDEX `uq_student_section` (`section_id` ASC, `student_id` ASC) VISIBLE,
  INDEX `section_id_idx` (`section_id` ASC) VISIBLE,
  INDEX `student_id_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_enrollments_section`
    FOREIGN KEY (`section_id`)
    REFERENCES `registrationdb`.`sections` (`section_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_enrollments_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `registrationdb`.`students` (`student_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2048
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`prerequisites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`prerequisites` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`prerequisites` (
  `prerequisite_course_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`prerequisite_course_id`, `course_id`),
  INDEX `course_id_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_prereq_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_prereq_required_course`
    FOREIGN KEY (`prerequisite_course_id`)
    REFERENCES `registrationdb`.`courses` (`course_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `registrationdb`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registrationdb`.`sessions` ;

CREATE TABLE IF NOT EXISTS `registrationdb`.`sessions` (
  `session_id` VARCHAR(128) NOT NULL,
  `user_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `expires_at` DATETIME NOT NULL,
  `ip_addr` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` VARCHAR(255) NULL DEFAULT NULL,
  `sess_ver` INT NOT NULL,
  `data` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `fk_session_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_session_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `registrationdb`.`users` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
