INSERT INTO `users` (`name`, `email`, `password_hash`) VALUES
('Christian Horner', 'horne_chri87@gmail.com', '$2b$10$pIlyp3XEcmfU8DeWU2mrLOME78CJIdd2yhrChPSO0VC6q42KuaxgG'),

('Toto Wolff', 'wolff_toto00@gmail.com', 'Password'),
('James Vowles', 'vowle_jame00@gmail.com', 'Password'),
('Zak Brown', 'brown_zak00@gmail.com', 'Password'),

('Max Verstappen', 'verst_max1@gmail.com', 'Password'),
('Sergio Perez', 'perez_serg11@gmail.com', 'Password'),
('Lewis Hamilton', 'hamil_lewi44@gmail.com', 'Password'),
('George Russell', 'russe_geor63@gmail.com', 'Password'),
('Charles Leclerc', 'lecle_char16@gmail.com', 'Password'),
('Carlos Sainz', 'sainz_carl55@gmail.com', 'Password'),
('Lando Norris', 'norri_land4@gmail.com', 'Password'),
('Oscar Piastri', 'piast_osca81@gmail.com', 'Password'),
('Fernando Alonso', 'alons_fern14@gmail.com', 'Password'),
('Lance Stroll', 'strol_lanc18@gmail.com', 'Password'),
('Pierre Gasly', 'gasly_pierr10@gmail.com', 'Password'),
('Esteban Ocon', 'ocon_este31@gmail.com', 'Password'),
('Yuki Tsunoda', 'tsuno_yuki22@gmail.com', 'Password'),
('Daniel Ricciardo', 'ricci_dani3@gmail.com', 'Password'),
('Valtteri Bottas', 'botta_valt77@gmail.com', 'Password'),
('Zhou Guanyu', 'zhou_guan24@gmail.com', 'Password'),
('Kevin Magnussen', 'magnu_kevi20@gmail.com', 'Password'),
('Nico Hulkenberg', 'hulke_nico27@gmail.com', 'Password'),
('Alexander Albon', 'albon_alex23@gmail.com', 'Password'),
('Logan Sargeant', 'sarge_loga2@gmail.com', 'Password'),
('Nyck de Vries', 'devri_nyck21@gmail.com', 'Password'),
('Liam Lawson', 'lawso_liam40@gmail.com', 'Password'),
('Kimi Raikkonen', 'raikk_kimi7@gmail.com', 'Password'),
('Sebastian Vettel', 'vette_seba5@gmail.com', 'Password'),
('Jenson Button', 'butto_jens22@gmail.com', 'Password'),
('Nico Rosberg', 'rosbe_nico6@gmail.com', 'Password'),
('Felipe Massa', 'massa_feli19@gmail.com', 'Password'),
('Rubens Barrichello', 'barri_rube11@gmail.com', 'Password'),
('Michael Schumacher', 'schum_mich47@gmail.com', 'Password'),
('Mick Schumacher', 'schum_mick47@gmail.com', 'Password'),
('Romain Grosjean', 'grosj_roma8@gmail.com', 'Password'),
('Pastor Maldonado', 'maldo_past18@gmail.com', 'Password'),
('Ayrton Senna', 'senna_ayrt12@gmail.com', 'Password'),
('Alain Prost', 'prost_alai1@gmail.com', 'Password'),
('Niki Lauda', 'lauda_niki12@gmail.com', 'Password'),
('Gerhard Berger', 'berge_gerh28@gmail.com', 'Password'),
('David Coulthard', 'coult_davi2@gmail.com', 'Password'),
('Mika Hakkinen', 'hakki_mika8@gmail.com', 'Password'),
('Jacques Villeneuve', 'ville_jacq27@gmail.com', 'Password'),
('Juan Pablo Montoya', 'monto_juan42@gmail.com', 'Password'),
('Kimi Antonelli', 'anton_kimi12@gmail.com', 'Password'),
('Oliver Bearman', 'bearm_oliv87@gmail.com', 'Password'),
('Jack Doohan', 'dooha_jack7@gmail.com', 'Password'),
('Theo Pourchaire', 'pourd_theo5@gmail.com', 'Password'),
('Callum Ilott', 'ilott_call12@gmail.com', 'Password'),
('Robert Kubica', 'kubic_robe88@gmail.com', 'Password');